name: maestro
version:             0.1.0.0
license:             BSD3
synopsis:            A graphic show of the master theorem
author:              Juan Miguel Vilar
maintainer:          jvilar@uji.es
copyright:           2018 Juan Miguel Vilar

data-files:
- maestro.glade

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: lib
  ghc-options:
    - -Wall
  dependencies:
    - diagrams-cairo
    - diagrams-core
    - diagrams-gi-gtk
    - diagrams-lib
    - haskell-gi-base
    - gi-gdk
    - gi-gtk
    - mtl
    - SVGFonts
    - text

executables:
  callTree:
    main: callTree.hs
    dependencies:
      - maestro
      - diagrams-cairo

  costDiagram:
    main: costDiagram.hs
    dependencies:
      - maestro
      - diagrams-cairo
      - diagrams-lib

  maestro:
    main:             maestro.hs
    dependencies:
    - gi-gtk
    - maestro
    - text

