name: maestro
version:             0.1.0.0
license:             GPL-2
synopsis:            A graphic show of the maestro theorem
author:              Juan Miguel Vilar
maintainer:          jvilar@uji.es
copyright:           2018 Juan Miguel Vilar

data-files:
- maestro.glade

dependencies:
- base >= 4.7 && < 5

executables:
  maestro:
    main:             maestro.hs
    dependencies:
    - cairo
    - diagrams-cairo
    - diagrams-core
    - diagrams-lib
    - gtk3
    - mtl
    - SVGFonts
    
