resolver: lts-22.26

nix:
  enable: true
  packages:
    - gobject-introspection
    - gtk3
    - libdatrie
    - libepoxy
    - libselinux
    - libsepol
    - libthai
    - libxkbcommon
    - pcre2
    - pkg-config
    - util-linux
    - xorg.libXdmcp
    - xorg.libXtst

allow-newer: true

extra-deps:
 - git: https://github.com/tkemps/diagrams-gi-gtk
   commit: ba48437dd6357c8e6624166e7131ed3b46743fcc

local-bin-path: .
